name: simple_worker
description: Simply offload work to another Isolate or group of Isolates in any Dart program or Flutter application.
version: 1.0.0
repository: https://github.com/TheCarpetMerchant/simple_worker

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
